package com.bank.islamic.sukukregistryandcustody;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Sukuk Registry And Custody
 *
 * Business Area:      Treasury Markets and Sukuk
 * Business Domain:    Sukuk
 * Functional Pattern: Administer
 * Asset Type:         Sukuk Holding
 * Control Record:     Sukuk Holding Administrative Plan
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Sukuk Registry And Custody — BIAN Semantic API")
                .description("Service Domain 'Sukuk Registry And Custody' (Administer pattern) "
                        + "operating on the 'Sukuk Holding Administrative Plan' control record.")
                .version("0.1.0"));
    }
}
